"""OpenAI-based narrative insight generation — an optional enhancement to
the demo path's template-generated ai_insight text (see config.py's
openai_api_key docstring).

Only ever called when execution_mode="demo" and OPENAI_API_KEY is set.
Unlike execution_mode=bigquery/snowflake's fail-fast contract, a failure
here does NOT fail the whole app at startup: OPENAI_API_KEY never changes
`source` (it stays "demo" — the ML computation is fully correct and
unaffected either way), it only tries to upgrade one supplementary text
field. A failed call is logged and the caller falls back to the template
sentence, keeping ai_insight_generated_by="template" — never "openai"
for text that wasn't actually generated by OpenAI.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from src.config import Settings

logger = logging.getLogger(__name__)


def enhance_with_openai(template_text: str, prompt: str, settings: "Settings") -> tuple[str, Literal["template", "openai"]]:
    """The single call site every service's _prepare_demo() uses. Returns
    (template_text, "template") unchanged when OPENAI_API_KEY is unset or
    the call fails — callers never need their own try/except, and the
    "never mislabel a template as openai-generated" contract lives in one
    place instead of being re-implemented per service.
    """
    if not settings.openai_api_key:
        return template_text, "template"
    generated = generate_insight(prompt, settings.openai_api_key, settings.openai_model)
    if generated:
        return generated, "openai"
    return template_text, "template"


def generate_insight(prompt: str, api_key: str, model: str) -> str | None:
    """Returns the generated text, or None if the call failed. Import of
    the openai package is local to this function so it need not be
    importable when OPENAI_API_KEY is unset (mirrors bigquery/client.py's
    and snowflake/client.py's local-import discipline for optional
    cloud dependencies)."""
    try:
        from openai import OpenAI  # noqa: PLC0415

        client = OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=200,
            temperature=0.4,
        )
        text = response.choices[0].message.content
        return text.strip() if text else None
    except Exception:  # noqa: BLE001
        logger.warning("OpenAI insight generation failed; falling back to template sentence", exc_info=True)
        return None
